service: myserverlessproject
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser

# upload the file using amazon-s3-sync
#For installing this plugin i have use npm install --save serverless-s3-sync
#adding a plugin https://www.serverless.com/plugins/serverless-s3-sync
# We can also use aws plugin to upload the file into the bucket
# 

plugins:
  - serverless-s3-sync
custom:
  s3Sync:
    - bucketName: myserverlessprojectuploadbuckt-321123
      localDir: UploadData    



functions:
  getUser:
    handler: lambdas/getUser.handler
    # if i want to make it an api I need to make some more adjustment to that file
    # using some events that is going to trigger this lambda


    events:
      - http:
            path: get-user/{ID} # to trigger the api whatever id user enter that will pass the path parameter.
            method: GET
            cors: true

# #creating a s3 bucket
# #https://stackoverflow.com/questions/41572237/how-can-we-use-serverless-yml-to-create-an-aws-s3-bucket-and-add-a-file-to-it

# resources:
#   Resources:
#     DemoBucketUpload:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: myserverlessprojectuploadbuckt-321123
